apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "sydo-2"
  annotations:
    backstage.io/managed-by: scaffolder
    github.com/project-slug: sotatek-cloudteam/backstage-demo1-12
    backstage.io/techdocs-ref: dir:.
spec:
  type: database
  owner: sotatek-dev-team
  lifecycle: experimental
